/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-fixed-variant": "#005321",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d8e3fb",
        "outline": "#6e7881",
        "on-primary-container": "#003751",
        "on-primary-fixed": "#001e2f",
        "surface": "#f9f9ff",
        "on-surface": "#111c2d",
        "primary-fixed": "#c9e6ff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#89ceff",
        "inverse-surface": "#263143",
        "inverse-primary": "#89ceff",
        "on-secondary-container": "#6f5900",
        "inverse-on-surface": "#ecf1ff",
        "secondary": "#735c00",
        "primary": "#006591",
        "surface-container": "#e7eeff",
        "on-secondary-fixed": "#231b00",
        "on-primary-fixed-variant": "#004c6e",
        "secondary-fixed": "#ffe083",
        "on-primary": "#ffffff",
        "outline-variant": "#bec8d2",
        "on-secondary-fixed-variant": "#574500",
        "on-error-container": "#93000a",
        "surface-dim": "#cfdaf2",
        "surface-bright": "#f9f9ff",
        "on-surface-variant": "#3e4850",
        "tertiary": "#006e2f",
        "background": "#f9f9ff",
        "tertiary-fixed-dim": "#4ae176",
        "on-background": "#111c2d",
        "secondary-fixed-dim": "#eec200",
        "surface-container-highest": "#d8e3fb",
        "tertiary-container": "#00b351",
        "primary-container": "#0ea5e9",
        "on-tertiary-container": "#003c16",
        "on-tertiary-fixed": "#002109",
        "surface-container-high": "#dee8ff",
        "secondary-container": "#fed01b",
        "error-container": "#ffdad6",
        "surface-tint": "#006591",
        "tertiary-fixed": "#6bff8f"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        quicksand: ["Quicksand", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
